### ISSUE TITLE
npm-link-by-copy will wipe out link source directory under some conditions

### ISSUE THREAD

**Issue by matdumsa** [slavivanov/npm-link-by-copy#1]
let's say you have a library, let's call it `something`

(from the something directory)
npm link

(from the consuming directory)
npm link something
npm-link-by-copy something

actual: everything in the something directory gets wiped (all files set empty, even the .git directory, you lose all changes that weren't pushed)
expected: the simlinked directory first to jump before the copy to be done.

**Comment by slavivanov** [comment]
Thank you for that!
