### ISSUE TITLE
Add watch, get rid of yargs, fs-extra

### ISSUE THREAD

**Issue by DesignByOnyx** [slavivanov/npm-link-by-copy#5]
Thanks for providing this module. I was curious if you would accept a PR for any or all of the following changes:

- add a watch on the source files and re-copy whenever they change. This would be more in line with with way `npm link` works as symlinks point to the original directory and the files therein.
- get rid of `yargs` and `fs-extra` - the code is simple enough that the extra dependencies are not needed. We could also get rid of `require-global-node-module` as it hasn't been updated in 5 years and is not really needed today.

**Comment by DesignByOnyx** [comment]
The project you forked has been moved and is currently maintained: https://github.com/laggingreflex/npm-link-better

I was mostly needing the `watch` behavior and was going to remove the other dependencies while I was at it.

**Comment by slavivanov** [comment]
Hi @DesignByOnyx, thanks for the suggestion. 
To be fair, I'm not paying much attention to this package. If the original one is maintained, it would be better if you submitted the improvements you mentioned there.
